### ISSUE TITLE
doesn t work

### ISSUE THREAD

**Issue by RusEu** [EddyVerbruggen/nativescript-mapbox-demo#1]
the app stops every time i click the show button..

**Comment by EddyVerbruggen** [comment]
Sorry didn't see this before. I've changed the repo in a few relevant places for this, and also NativeScript has evolved since, so please test again and reopen if the problem remains. I just tested with NS 1.7.0 and it's all fine on both platforms.

**Comment by dklinzing** [comment]
seems like something is still wrong.  i get an error after I click the show button.

**Comment by EddyVerbruggen** [comment]
@dklinzing care to elaborate?

**Comment by dklinzing** [comment]
Here's the error I'm getting: Error in mapbox.show: Error: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.nativescript.mapboxdemo-1/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.mapboxdemo-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libmapbox-gl.so"
