### ISSUE TITLE
Can't install the demo : npm ERR! addLocal Could not install

### ISSUE THREAD

**Issue by Neomac** [EddyVerbruggen/nativescript-mapbox-demo#2]
Hi, I wanted to try the Mapbox plugin and I found your demo project.
I'd loved to test it but I can't make it run, when I do a "tns install" I have : 
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm WARN package.json @ No license field.
npm ERR! addLocal Could not install ~/Documents/nativescript-mapbox
ENOENT: no such file or directory, open '~/Documents/nativescript-mapbox'
# install

Was thinking it failed because of the mismatch between the folder name nativescript-mapbox and the folder created in the repo which is named nativescript-mapbox-demo. But replacing all occurrences of nativescript-mapbox didn't change anything.

I also tried to update my npm as I found it maybe related but it hasn't solved the issue either.

I have the latest version of native script (2.0.0) install and have other apps running well

Do you have any clue of what's going wrong?

**Comment by EddyVerbruggen** [comment]
Did you do these steps (including the last one) before running `tns install`?

```
$ git clone https://github.com/EddyVerbruggen/nativescript-mapbox-demo
$ cd nativescript-mapbox-demo
$ cd Mapbox
```

**Comment by Neomac** [comment]
Yep followed exactly the steps in the installation process.

**Comment by EddyVerbruggen** [comment]
Thx, I'll take a look!

**Comment by EddyVerbruggen** [comment]
`package.json` expected a locallly cloned plugin repo instead of the one on npm. I checked that in while updating the last version of the plugin. Sorry for the inconvenience!

**Comment by Neomac** [comment]
Ok, thx for the fix.
