### ISSUE TITLE
Markers do not show Title and Sub-title on iOS

### ISSUE THREAD

**Issue by ickata** [EddyVerbruggen/nativescript-mapbox-demo#3]
Hi,

I cannot see the Title and Sub-title of a marker, no matter how hard I try to tap on it. Testing on iOS Simulator (iPhone 6).

BTW - can I hook to a `cameraChange` event or something?

**Comment by burkeholland** [comment]
Confirmed. I don't see them either. Are they supposed to appear automatically?

**Comment by EddyVerbruggen** [comment]
Yeah supposed to appear upon tapping it as on Android. A bit hard for me to verify/fix atm (vacation).

**Comment by EddyVerbruggen** [comment]
Fixed a while ago.
