### ISSUE TITLE
mapbox show error: TypeError: Cannot read property 'addView' of null

### ISSUE THREAD

**Issue by MikeHuntington** [EddyVerbruggen/nativescript-mapbox-demo#4]
Hello, I'm able to run this plugin perfectly on my iOS build... but when I run on Android, the follow console error is thrown.

JS: Error in mapbox.show: TypeError: Cannot read property 'addView' of null
JS: mapbox show error: TypeError: Cannot read property 'addView' of null

**Comment by MikeHuntington** [comment]
Closed this issue.. sorry I thought I was in the main nativescript-mapbox repo

**Comment by jiwonyune** [comment]
How did you fix this problem? I have the same problem.
