### ISSUE TITLE
App crash after typing map show button

### ISSUE THREAD

**Issue by smartcris** [EddyVerbruggen/nativescript-mapbox-demo#5]
I'm using Genymotion with a Samsung Galaxy S4 - 4.4.4 - API 19 1080x1920 on Windows 10
After cloning the repo and running tns install I get the following log: 

`D:\websites\nativescript-mapbox-demo\Mapbox>tns run android --emulator
Executing before-prepare hook from D:\websites\nativescript-mapbox-demo\Mapbox\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 1.8.10
WARNING: The file: D:\websites\nativescript-mapbox-demo\Mapbox\node_modules\nativescript-mapbox\platforms\android\AndroidManifest.xml is depricated, you can read more about what will be the expected plugin structure here: https://www.nativescript.org/blog/migrating-n-android-plugins-from-version-1.7-to-2.0

:config phase:  createDefaultIncludeFiles

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
        +adding dependency: D:\websites\nativescript-mapbox-demo\Mapbox\platforms\android\libs\aar\widgets-release.aar
:deleteMetadata
:deleteFlavors
:clean UP-TO-DATE

BUILD SUCCESSFUL

Total time: 5.941 secs
Successfully prepared plugin nativescript-mapbox for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Project successfully prepared
WARNING: The file: D:\websites\nativescript-mapbox-demo\Mapbox\node_modules\nativescript-mapbox\platforms\android\AndroidManifest.xml is depricated, you can read more about what will be the expected plugin structure here: https://www.nativescript.org/blog/migrating-n-android-plugins-from-version-1.7-to-2.0

:config phase:  createDefaultIncludeFiles
        +found plugins: nativescript-mapbox
Renaming plugin directory to flavor name: D:\websites\nativescript-mapbox-demo\Mapbox\platforms\android\src\nativescript-mapbox -> D:\websites\nativescript-mapbox-demo\Mapbox\platforms\android\src\F0
        +found plugins: tns-core-modules-widgets
         + creating include.gradle file for D:\websites\nativescript-mapbox-demo\Mapbox\platforms\android\configurations\tns-core-modules-widgets
Renaming plugin directory to flavor name: D:\websites\nativescript-mapbox-demo\Mapbox\platforms\android\src\tns-core-modules-widgets -> D:\websites\nativescript-mapbox-demo\Mapbox\platforms\android\src\F1

:config phase:  createPluginsConfigFile
         Creating product flavors include.gradle file in D:\websites\nativescript-mapbox-demo\Mapbox\platforms\android/configurations folder...

:config phase:  pluginExtend
        +applying configuration from: D:\websites\nativescript-mapbox-demo\Mapbox\platforms\android\configurations\include.gradle
        +applying configuration from: D:\websites\nativescript-mapbox-demo\Mapbox\platforms\android\configurations\nativescript-mapbox\include.gradle
        +applying configuration from: D:\websites\nativescript-mapbox-demo\Mapbox\platforms\android\configurations\tns-core-modules-widgets\include.gradle

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
        +adding dependency: D:\websites\nativescript-mapbox-demo\Mapbox\platforms\android\libs\aar\widgets-release.aar
:preBuild UP-TO-DATE
:preF0F1DebugBuild UP-TO-DATE
:checkF0F1DebugManifest
:preF0F1ReleaseBuild UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2340Library
:prepareComAndroidSupportAppcompatV72340Library
:prepareComAndroidSupportDesign2340Library
:prepareComAndroidSupportRecyclerviewV72340Library
:prepareComAndroidSupportSupportV42340Library
:prepareComAndroidSupportSupportVectorDrawable2340Library
:prepareComMapboxMapboxsdkMapboxAndroidSdk410Library
:prepareComMapzenAndroidLost110Library
:prepareMapboxdemoBindingGeneratorUnspecifiedLibrary
:prepareMapboxdemoRuntimeUnspecifiedLibrary
:prepareWidgetsReleaseLibrary
:prepareF0F1DebugDependencies
:compileF0F1DebugAidl
:compileF0F1DebugRenderscript
:generateF0F1DebugBuildConfig
:cleanLocalAarFiles
:ensureMetadataOutDir
:collectAllJars
:setProperties
:asbg:generateInterfaceNamesList
:asbg:runAstParser
inputDir: D:\websites\nativescript-mapbox-demo\Mapbox\platforms\android\src\main\assets\app
                                                                                            outFile: ../bindings.txt
                                                                                                                     :asbg:generateBindings
:generateF0F1DebugAssets UP-TO-DATE
:mergeF0F1DebugAssets
:generateF0F1DebugResValues
:generateF0F1DebugResources
:mergeF0F1DebugResources
:processF0F1DebugManifest
:processF0F1DebugResources
:generateF0F1DebugSources
:compileF0F1DebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:compileF0F1DebugNdk UP-TO-DATE
:compileF0F1DebugSources
:buildMetadata
Skip okio.Okio
        Error: java.lang.NullPointerException
 'assets/metadata/treeNodeStream.dat' NOT FOUND
 'assets/metadata/treeStringsStream.dat' NOT FOUND
 'assets/metadata/treeValueStream.dat' NOT FOUND
 'assets/metadata/treeNodeStream.dat'...
 'assets/metadata/treeStringsStream.dat'...
 'assets/metadata/treeValueStream.dat'...
:transformClassesWithDexForF0F1Debug
:mergeF0F1DebugJniLibFolders
:transformNative_libsWithMergeJniLibsForF0F1Debug
:processF0F1DebugJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForF0F1Debug
:validateDebugSigning
:packageF0F1Debug
:zipalignF0F1Debug
:assembleF0F1Debug
:assembleDebug
:buildapk

BUILD SUCCESSFUL

Total time: 55.716 secs
Project successfully built
Successfully deployed on device with identifier '192.168.181.101:5555'.
`
After pressing map show button I get this logs in my console, and the application crash.

`E/FusionEngine( 3482):  at com.tns.Runtime.callJSMethodNative(Native Method)
E/FusionEngine( 3482):  at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:861)
E/FusionEngine( 3482):  at com.tns.Runtime.callJSMethodImpl(Runtime.java:726)
E/FusionEngine( 3482):  at com.tns.Runtime.callJSMethod(Runtime.java:712)
E/FusionEngine( 3482):  at com.tns.Runtime.callJSMethod(Runtime.java:693)
E/FusionEngine( 3482):  at com.tns.Runtime.callJSMethod(Runtime.java:683)
E/FusionEngine( 3482):  at com.tns.Runtime.callJSMethodNative(Native Method)
E/FusionEngine( 3482):  at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:861)
E/FusionEngine( 3482):  at com.tns.Runtime.callJSMethodImpl(Runtime.java:726)
E/FusionEngine( 3482):  at com.tns.Runtime.callJSMethod(Runtime.java:712)
E/FusionEngine( 3482):  at com.tns.Runtime.callJSMethod(Runtime.java:693)
E/FusionEngine( 3482):  at com.tns.Runtime.callJSMethod(Runtime.java:683)`

**Comment by EddyVerbruggen** [comment]
Can you run `adb logcat` and paste the relevant portion of the log here? There's nothing in your post that relates to the crash.

**Comment by smartcris** [comment]
Here we go :

D:\websites\nativescript-mapbox-demo\Mapbox>adb logcat
--------- beginning of /dev/log/main
D/dalvikvm( 4716): GC_CONCURRENT freed 244K, 11% free 3273K/3672K, paused 1ms+0ms, total 4ms
D/dalvikvm( 4716): GC_CONCURRENT freed 296K, 12% free 3399K/3848K, paused 0ms+0ms, total 3ms
D/dalvikvm( 4716): GC_CONCURRENT freed 283K, 12% free 3521K/3960K, paused 2ms+0ms, total 4ms
D/dalvikvm( 4716): GC_FOR_ALLOC freed 76K, 11% free 3537K/3960K, paused 1ms, total 2ms
I/dalvikvm-heap( 4716): Grow heap (frag case) to 8.575MB for 5214828-byte allocation
D/dalvikvm( 4716): GC_FOR_ALLOC freed <1K, 5% free 8629K/9056K, paused 2ms, total 2ms
D/dalvikvm( 4716): GC_CONCURRENT freed <1K, 5% free 8629K/9056K, paused 0ms+1ms, total 2ms
D/dalvikvm( 4716): GC_FOR_ALLOC freed 203K, 5% free 8877K/9280K, paused 2ms, total 2ms
I/dalvikvm-heap( 4716): Grow heap (frag case) to 11.237MB for 2536932-byte allocation
D/dalvikvm( 4716): GC_CONCURRENT freed <1K, 4% free 11354K/11760K, paused 2ms+0ms, total 4ms
D/dalvikvm( 4716): DexOpt: --- BEGIN 'android.support.v4.view.ViewPager_SimpleOnPageChangeListener_frnal_ts_helpers_l55_c38__PageChangedListener-1469887928777-1.jar' (bootstrap=0) ---
D/dalvikvm( 4745): DexOpt: load 0ms, verify+opt 0ms, 83612 bytes
D/dalvikvm( 4716): DexOpt: --- END 'android.support.v4.view.ViewPager_SimpleOnPageChangeListener_frnal_ts_helpers_l55_c38__PageChangedListener-1469887928777-1.jar' (success) ---
D/dalvikvm( 4716): DEX prep '/data/data/org.nativescript.mapboxdemo/code_cache/secondary-dexes/android.support.v4.view.ViewPager_SimpleOnPageChangeListener_frnal_ts_helpers_l55_c38__PageChangedListener-1469887928777-1.jar': unzip in 0ms, rewrite 11ms
D/dalvikvm( 4716): DexOpt: --- BEGIN 'android.support.v4.view.PagerAdapter_frnal_ts_helpers_l55_c38__PagerAdapterClassInner-1469887928777-1.jar' (bootstrap=0) ---
D/dalvikvm( 4746): DexOpt: load 0ms, verify+opt 0ms, 84060 bytes
D/dalvikvm( 4716): DexOpt: --- END 'android.support.v4.view.PagerAdapter_frnal_ts_helpers_l55_c38__PagerAdapterClassInner-1469887928777-1.jar' (success) ---
D/dalvikvm( 4716): DEX prep '/data/data/org.nativescript.mapboxdemo/code_cache/secondary-dexes/android.support.v4.view.PagerAdapter_frnal_ts_helpers_l55_c38__PagerAdapterClassInner-1469887928777-1.jar': unzip in 0ms, rewrite 11ms
I/dalvikvm( 4716): Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
W/dalvikvm( 4716): VFY: unable to resolve virtual method 494: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
D/dalvikvm( 4716): VFY: replacing opcode 0x6e at 0x0002
I/dalvikvm( 4716): Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
W/dalvikvm( 4716): VFY: unable to resolve virtual method 516: Landroid/content/res/TypedArray;.getType (I)I
D/dalvikvm( 4716): VFY: replacing opcode 0x6e at 0x0002
I/dalvikvm( 4716): Could not find method android.content.res.Resources.getDrawable, referenced from method android.support.v7.widget.ResourcesWrapper.getDrawable
W/dalvikvm( 4716): VFY: unable to resolve virtual method 457: Landroid/content/res/Resources;.getDrawable (ILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
D/dalvikvm( 4716): VFY: replacing opcode 0x6e at 0x0002
I/dalvikvm( 4716): Could not find method android.content.res.Resources.getDrawableForDensity, referenced from method android.support.v7.widget.ResourcesWrapper.getDrawableForDensity
W/dalvikvm( 4716): VFY: unable to resolve virtual method 459: Landroid/content/res/Resources;.getDrawableForDensity (IILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
D/dalvikvm( 4716): VFY: replacing opcode 0x6e at 0x0002
D/libEGL  ( 4716): loaded /system/lib/egl/libEGL_genymotion.so
D/        ( 4716): HostConnection::get() New Host Connection established 0xb82d60a8, tid 4716
D/libEGL  ( 4716): loaded /system/lib/egl/libGLESv1_CM_genymotion.so
D/libEGL  ( 4716): loaded /system/lib/egl/libGLESv2_genymotion.so
W/EGL_genymotion( 4716): eglSurfaceAttrib not implemented
E/OpenGLRenderer( 4716): Getting MAX_TEXTURE_SIZE from GradienCache
E/OpenGLRenderer( 4716): MAX_TEXTURE_SIZE: 16384
E/OpenGLRenderer( 4716): Getting MAX_TEXTURE_SIZE from Caches::initConstraints()
E/OpenGLRenderer( 4716): MAX_TEXTURE_SIZE: 16384
D/OpenGLRenderer( 4716): Enabling debug mode 0
--------- beginning of /dev/log/system
D/MobileDataStateTracker( 1635): default: setPolicyDataEnable(enabled=true)
D/MobileDataStateTracker( 1635): default: setPolicyDataEnable(enabled=true)
I/ActivityManager( 1635): Displayed org.nativescript.mapboxdemo/com.tns.NativeScriptActivity: +844ms
W/genymotion_audio( 1305): out_write() limiting sleep time 46802 to 39909
I/MapboxEventManager( 4716): Telemetry initialize() called...
I/MapboxEventManager( 4716): Right before Telemetry set enabled in initialized()
I/MapboxEventManager( 4716): setTelemetryEnabled(); this.telemetryEnabled = false; telemetryEnabled = true
D/MapboxEventManager( 4716): Starting Telemetry Up!
I/MapboxEventManager( 4716): Permissions are good, see if GPS is enabled and if not then setup Ambient.
E/MapboxEventManager( 4716): Error Trying to load Staging Credentials: java.lang.NullPointerException
D/dalvikvm( 4716): Trying to load lib /data/app-lib/org.nativescript.mapboxdemo-1/libmapbox-gl.so 0xa50016d8
D/dalvikvm( 4716): Added shared lib /data/app-lib/org.nativescript.mapboxdemo-1/libmapbox-gl.so 0xa50016d8
D/dalvikvm( 4716): Trying to load lib /data/app-lib/org.nativescript.mapboxdemo-1/libmapbox-gl.so 0xa50016d8
D/dalvikvm( 4716): Shared lib '/data/app-lib/org.nativescript.mapboxdemo-1/libmapbox-gl.so' already loaded in same CL 0xa50016d8
I/dalvikvm( 4716): threadid=1: recursive native library load attempt (/data/app-lib/org.nativescript.mapboxdemo-1/libmapbox-gl.so)
D/dalvikvm( 4716): Trying to load lib /data/app-lib/org.nativescript.mapboxdemo-1/libmapbox-gl.so 0xa50016d8
D/dalvikvm( 4716): Shared lib '/data/app-lib/org.nativescript.mapboxdemo-1/libmapbox-gl.so' already loaded in same CL 0xa50016d8
I/dalvikvm( 4716): threadid=1: recursive native library load attempt (/data/app-lib/org.nativescript.mapboxdemo-1/libmapbox-gl.so)
F/libc    ( 4716): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=128), thread 4755 (ript.mapboxdemo)
I/DEBUG   ( 1279): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   ( 1279): Build fingerprint: 'generic/vbox86p/vbox86p:4.4.4/KTU84P/eng.genymotion.20160609.162149:userdebug/test-keys'
I/DEBUG   ( 1279): Revision: '0'
I/DEBUG   ( 1279): pid: 4716, tid: 4755, name: ript.mapboxdemo  >>> org.nativescript.mapboxdemo <<<
I/DEBUG   ( 1279): signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 00000000
I/DEBUG   ( 1279):     eax b8388fe8  ebx 915b823c  ecx 00002b99  edx 00000001
I/DEBUG   ( 1279):     esi 0000000e  edi b8388bf8
I/DEBUG   ( 1279):     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
I/DEBUG   ( 1279):     eip 9132a33b  ebp 910e9a98  esp 910e9a80  flags 00210286
E/Corkscrew( 1279): unrecognized dwarf lower part encoding: 0x22
I/DEBUG   ( 1279):
I/DEBUG   ( 1279): backtrace:
I/DEBUG   ( 1279):     #00  pc 0024033b  /data/app-lib/org.nativescript.mapboxdemo-1/libmapbox-gl.so
I/BootReceiver( 1635): Copying /data/tombstones/tombstone_07 to DropBox (SYSTEM_TOMBSTONE)
D/        ( 1635): HostConnection::get() New Host Connection established 0xb834aaf8, tid 4756
W/ActivityManager( 1635):   Force finishing activity org.nativescript.mapboxdemo/com.tns.NativeScriptActivity
D/Zygote  ( 1304): Process 4716 terminated by signal (11)
W/InputDispatcher( 1635): channel '5297deac org.nativescript.mapboxdemo/com.tns.NativeScriptActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher( 1635): channel '5297deac org.nativescript.mapboxdemo/com.tns.NativeScriptActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
D/dalvikvm( 1635): GC_FOR_ALLOC freed 2745K, 27% free 17982K/24368K, paused 6ms, total 6ms
W/InputDispatcher( 1635): Attempted to unregister already unregistered input channel '5297deac org.nativescript.mapboxdemo/com.tns.NativeScriptActivity (server)'
I/WindowState( 1635): WIN DEATH: Window{5297deac u0 org.nativescript.mapboxdemo/com.tns.NativeScriptActivity}
W/ActivityManager( 1635): Exception thrown during pause
W/ActivityManager( 1635): android.os.DeadObjectException
W/ActivityManager( 1635):       at android.os.BinderProxy.transact(Native Method)
W/ActivityManager( 1635):       at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:660)
W/ActivityManager( 1635):       at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:761)
W/ActivityManager( 1635):       at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2443)
W/ActivityManager( 1635):       at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2320)
W/ActivityManager( 1635):       at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2050)
W/ActivityManager( 1635):       at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:9548)
W/ActivityManager( 1635):       at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:9441)
W/ActivityManager( 1635):       at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:10086)
W/ActivityManager( 1635):       at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:9637)
W/ActivityManager( 1635):       at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
I/ActivityManager( 1635): Process org.nativescript.mapboxdemo (pid 4716) has died.
W/ActivityManager( 1635): Scheduling restart of crashed service org.nativescript.mapboxdemo/com.mapbox.mapboxsdk.telemetry.TelemetryService in 1000ms
D/MobileDataStateTracker( 1635): default: setPolicyDataEnable(enabled=true)
W/EGL_genymotion( 1827): eglSurfaceAttrib not implemented
D/MobileDataStateTracker( 1635): default: setPolicyDataEnable(enabled=true)
D/MobileDataStateTracker( 1635): default: setPolicyDataEnable(enabled=true)
D/dalvikvm( 4762): Late-enabling CheckJNI
D/dalvikvm( 4762): Trying to load lib /data/app-lib/org.nativescript.mapboxdemo-1/libNativeScript.so 0xa5002260
I/ActivityManager( 1635): Start proc org.nativescript.mapboxdemo for service org.nativescript.mapboxdemo/com.mapbox.mapboxsdk.telemetry.TelemetryService: pid=4762 uid=10066 gids={50066, 1028, 1015, 3003}
D/dalvikvm( 4762): Added shared lib /data/app-lib/org.nativescript.mapboxdemo-1/libNativeScript.so 0xa5002260
I/TNS.Native( 4762): NativeScript Runtime Version 2.1.1, commit bce725184f249812c73163957aa50aa9339edddb
D/TNS.Native( 4762): JNI_ONLoad
D/TNS.Native( 4762): JNI_ONLoad END
D/TNS.Native( 4762): V8 version 4.7.80
D/TNS.Native( 4762): lenNodes=68472, lenNames=724826, lenValues=873169
D/TNS.Native( 4762): time=2
D/TNS.Java( 4762): Enabling NativeScript Debugger Agent
D/dalvikvm( 4762): GC_CONCURRENT freed 271K, 12% free 3248K/3676K, paused 0ms+0ms, total 2ms
D/dalvikvm( 4762): GC_CONCURRENT freed 314K, 13% free 3336K/3804K, paused 0ms+0ms, total 2ms
I/TelemetryService( 4762): onCreate() called
I/TelemetryService( 4762): onStartCommand() called
D/MobileDataStateTracker( 1635): default: setPolicyDataEnable(enabled=true)
D/MobileDataStateTracker( 1635): default: setPolicyDataEnable(enabled=true)
D/MobileDataStateTracker( 1635): default: setPolicyDataEnable(enabled=true)
D/MobileDataStateTracker( 1635): default: setPolicyDataEnable(enabled=true)
D/MobileDataStateTracker( 1635): default: setPolicyDataEnable(enabled=true)
D/MobileDataStateTracker( 1635): default: setPolicyDataEnable(enabled=true)
D/MobileDataStateTracker( 1635): default: setPolicyDataEnable(enabled=true)
D/MobileDataStateTracker( 1635): default: setPolicyDataEnable(enabled=true)
D/MobileDataStateTracker( 1635): default: setPolicyDataEnable(enabled=true)
W/Binder  ( 1767): Caught a RuntimeException from the binder stub implementation.
W/Binder  ( 1767): java.lang.NullPointerException
W/Binder  ( 1767):      at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
W/Binder  ( 1767):      at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
W/Binder  ( 1767):      at android.os.Binder.execTransact(Binder.java:404)
W/Binder  ( 1767):      at dalvik.system.NativeStart.run(Native Method)
W/InputMethodManagerService( 1635): Got RemoteException sending setActive(false) notification to pid 4716 uid 10066
D/ConnectivityService( 1635): Sampling interval elapsed, updating statistics ..
D/ConnectivityService( 1635): Done.
D/ConnectivityService( 1635): Setting timer for 720seconds
D/dalvikvm( 1691): GC_CONCURRENT freed 4568K, 22% free 17207K/21928K, paused 3ms+1ms, total 20ms
W/Genyd   (   75): Can't parse request
W/Genyd   (   75): Can't parse request
W/Genyd   (   75): Can't parse request
D/Genyd   (   75): Received Set Clipboard
D/Genymotion(   75): Received Set Clipboard
D/MDnsDS  ( 1302): MDnsSdListener::Monitor poll timed out
D/MDnsDS  ( 1302): Going to poll with pollCount 1
D/dalvikvm( 1810): GC_CONCURRENT freed 454K, 15% free 3675K/4292K, paused 1ms+1ms, total 10ms
I/ActivityManager( 1635): Killing 3760:com.android.externalstorage/u0a6 (adj 15): empty for 1828s
I/ActivityManager( 1635): Killing 3743:android.process.media/u0a5 (adj 15): empty for 1828s
I/ActivityManager( 1635): Killing 3966:org.nativescript.bluetoothdemo/u0a58 (adj 15): empty for 1815s
I/ActivityManager( 1635): Killing 3929:com.android.quicksearchbox/u0a50 (adj 15): empty for 1838s
I/WindowState( 1635): WIN DEATH: Window{5299687c u0 com.android.quicksearchbox/com.android.quicksearchbox.SearchActivity EXITING}
D/ConnectivityService( 1635): Sampling interval elapsed, updating statistics ..
D/ConnectivityService( 1635): Done.
D/ConnectivityService( 1635): Setting timer for 720seconds
D/dalvikvm( 1691): GC_CONCURRENT freed 4568K, 22% free 17207K/21928K, paused 3ms+1ms, total 20ms
W/Genyd   (   75): Can't parse request
W/Genyd   (   75): Can't parse request
W/Genyd   (   75): Can't parse request
D/Genyd   (   75): Received Set Clipboard
D/Genymotion(   75): Received Set Clipboard
D/MDnsDS  ( 1302): MDnsSdListener::Monitor poll timed out
D/MDnsDS  ( 1302): Going to poll with pollCount 1
D/dalvikvm( 1810): GC_CONCURRENT freed 454K, 15% free 3675K/4292K, paused 1ms+1ms, total 10ms
I/ActivityManager( 1635): Killing 3760:com.android.externalstorage/u0a6 (adj 15): empty for 1828s
I/ActivityManager( 1635): Killing 3743:android.process.media/u0a5 (adj 15): empty for 1828s
I/ActivityManager( 1635): Killing 3966:org.nativescript.bluetoothdemo/u0a58 (adj 15): empty for 1815s
I/ActivityManager( 1635): Killing 3929:com.android.quicksearchbox/u0a50 (adj 15): empty for 1838s
I/WindowState( 1635): WIN DEATH: Window{5299687c u0 com.android.quicksearchbox/com.android.quicksearchbox.SearchActivity EXITING}
D/ConnectivityService( 1635): Sampling interval elapsed, updating statistics ..
D/ConnectivityService( 1635): Done.
D/ConnectivityService( 1635): Setting timer for 720seconds
W/Genyd   (   75): Can't parse request
D/Genyd   (   75): Received Set Clipboard
D/Genymotion(   75): Received Set Clipboard
I/EntropyMixer( 1635): Writing entropy...
D/dalvikvm( 1635): GC_CONCURRENT freed 2743K, 23% free 18851K/24368K, paused 6ms+2ms, total 30ms
I/ProcessStatsService( 1635): Prepared write state in 6ms
I/ProcessStatsService( 1635): Pruning old procstats: /data/system/procstats/state-2016-07-20-02-00-00.bin

**Comment by EddyVerbruggen** [comment]
Doesn't immediately ring a bell.. will need to investigate this further but I'm currently on vacation.
