### ISSUE TITLE
typescript angular 2

### ISSUE THREAD

**Issue by fkornel** [EddyVerbruggen/nativescript-mapbox-demo#6]
Are you planning to port the demo application to Nativescript + Angular?

**Comment by EddyVerbruggen** [comment]
No, but I could add an example to the readme.

**Comment by ahalls** [comment]
I'm trying to define the Mapbox view with Typescript/Angular2 from HTML

in `main.ts`

```
var map = require("natinescript-mapbox");
import {registerElement} from "nativescript-angular/element-registry";



registerElement("Map", () => map.Mapbox);
```

In the html file:

```
<ContentView  #mapcontentview height="100%">
   <Map
    accessToken=ACCESS_TOKEN 
    latitude="52.3702160"
    longitude="4.8951680"
    zoomLevel="3"
    mapStyle="light"
    hideAttribution="false"
    showUserLocation="true"
    hideCompass="false">
    </Map>
</ContentView>

```

**Comment by EddyVerbruggen** [comment]
Check [this sample](https://github.com/tsonevn/NGMapBoxTest)

To make it work though you'll need to use the plugin from github, or wait until 2.3.0 is released to npm later today.

**Comment by fkornel** [comment]
Thank you!
